server:
  port: 8090

spring:
  # config:
  #   import: optional:configserver:http://localhost:8888
  application:
    name: meself-usuarios
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meselfdb
    username: root
    password: Soluciones01
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
# Configuracion para conectarlo con eureka
# eureka:
#   instance:
#     hostname: localhost
#   client:
#     service-url:
#       default-zone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.web: DEBUG